name:                hnixtest
version:             0.1.0.0
github:              "githubuser/hnixtest"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hnixtest#readme>

dependencies:
- base >= 4.7 && < 5
# - cleff
# - cleff-plugin
# - polysemy
# - polysemy-plugin


library:
  source-dirs: src

# ghc-options:
# - -Wall
# - -Werror
# - -O2
# - -fplugin=Cleff.Plugin
# - -fplugin=Polysemy.Plugin



executables:
  hnixtest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -Wall
    # - -Werror
    # - -O2
    # - -fplugin=Cleff.Plugin
    # - -fplugin=Polysemy.Plugin
    dependencies:
    - hnixtest

tests:
  hnixtest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hnixtest
